name: "New Project Initialization"
description: "Standard workflow for starting a new project"
version: "1.0"

triggers:
  - type: "task"
    pattern: "PROJECT-*-INIT"
    status: "TODO"

steps:
  - id: "design"
    name: "Architecture Design"
    assigned: "architect"
    timeout: "2h"
    tasks:
      - "Query RAG for similar projects"
      - "Create architecture design"
      - "Document decisions in knowledge/decisions/"
      - "Create README.md with full specification"
      - "Break down into implementation tasks"
    outputs:
      - "README.md in project directory"
      - "Task breakdown in ACTIVE_TASKS.json"
      - "Architecture decision record"
    
  - id: "setup"
    name: "Project Setup"
    assigned: "builder"
    depends_on: ["design"]
    timeout: "1h"
    tasks:
      - "Create project directory"
      - "Initialize with framework (Next.js, Vite, etc.)"
      - "Run npm install"
      - "Verify dependencies installed"
      - "Create initial commit"
    verification:
      - tool: "verify_npm_install"
        expected: { hasNodeModules: true }
      - tool: "bash"
        command: "git log --oneline | head -1"
        
  - id: "implement"
    name: "Core Implementation"
    assigned: "builder"
    depends_on: ["setup"]
    timeout: "4h"
    tasks:
      - "Implement core features per architect design"
      - "Add error handling"
      - "Create reusable components"
      - "Commit every 30-60 minutes"
    verification:
      - tool: "verify_server_running"
        port: 3000
        
  - id: "test"
    name: "Testing & Validation"
    assigned: "validator"
    depends_on: ["implement"]
    timeout: "2h"
    tasks:
      - "Write unit tests"
      - "Write integration tests"
      - "Test all features"
      - "Take screenshots of UI"
      - "Performance testing"
    outputs:
      - "Test results in task update"
      - "Screenshots in project directory"
      - "Performance metrics"
      
  - id: "approve"
    name: "Final Approval"
    assigned: "orchestrator"
    depends_on: ["test"]
    timeout: "30m"
    tasks:
      - "Review all outputs"
      - "Verify all tests passing"
      - "Check deployment readiness"
      - "Merge to main if approved"

notifications:
  on_step_complete:
    - type: "broadcast"
      message: "Step {{step.name}} completed by {{step.assigned}}"
  on_workflow_complete:
    - type: "update_task"
      status: "COMPLETED"
      add_proof: true